### ISSUE TITLE
Мод крашит игру

### ISSUE THREAD

**Issue by odzirydzidzina** [EnergoStalin/AutoAuthMC#1]
При попытке зайти на сервер/в одиночную игру крашится, через modmenu не настраивается. Возможно я просто не нашёл, где его можно настроить. Есть ли конфиг, где можно указать пароль, который нужно вводить?

**Comment by EnergoStalin** [comment]
Для открытия файла с паролями используется команда [/aapasswords](https://github.com/EnergoStalin/AutoAuthMC/blob/8283011a29ab778da5daa1499fff135485b0c252/src/main/java/ru/energostalin/autoauth/AutoAuth.kt#L13) если сервер просит залогинится а пароля для этого сервера + ника не найдено в чате появляется кликабельная надпись ссылающаяся на эту команду. Это единственная настройка на данный момент.

Могу подтвердить что мод крашится(просто заменил иконку и перебилдил что же моглой пойти не так) до завтра пропатчу а пока можешь откатиться на предыдущую версию единственное изменение между двумя последними это иконка.

**Comment by EnergoStalin** [comment]
No way я папку не создаю можно починить вручную создав папку .../.minecraft/config/AutoAuth/
